### ISSUE TITLE
Change namespace url to be resolvable

### ISSUE THREAD

**Issue by jgrieb** [tibonto/DFG-Fachsystematik-Ontology#10]
Are there any plans to change the namespace so that the IRIs in the ontology become resolvable? E.g. `<https://github.com/tibonto/dfgfo>` is not very linked data-friendly.

If not, a possible solution would be a persistent identifier with redirecting via w3id. See for a example "The Software Description Ontology" (sdo), which is also hosted at github / github pages, and the ontology namespace `https://w3id.org/okn/o/sd/1.4.0` simply redirects there. Content-negotiation is also supported, e.g.:
` curl -Lv "https://w3id.org/okn/o/sd/1.4.0" -H "accept: application/rdf+xml" ` redirects to the XML version of the ontology
` curl -Lv "https://w3id.org/okn/o/sd/1.4.0" -H "accept: text/turtle" ` redirects to the ttl, and so on...

Registering at w3id seems to be simple: https://w3id.org/#new
The configuration for the sdo is here: https://github.com/perma-id/w3id.org/blob/master/okn/o/sd/.htaccess 
Or also NFDI4Ing: https://github.com/perma-id/w3id.org/blob/master/nfdi4ing/metadata4ing/.htaccess

**Comment by SArndt-TIB** [comment]
Dear Jonas, thanks for your suggestion. It is definitely one of the steps which should be done here soon. Might be purl.org as well. I'll notify you, when it is available. For simple imports, you could use <https://raw.githubusercontent.com/tibonto/DFG-Fachsystematik-Ontology/main/dfgfo.ttl> for now.

**Comment by SArndt-TIB** [comment]
FYI: This issue is not fully done yet, but most of the prep work is done.
