### ISSUE TITLE
Versioning the DFG-Fachsystematik

### ISSUE THREAD

**Issue by doigl** [tibonto/DFG-Fachsystematik-Ontology#13]
Is there any idea or are there any plans, how to handle the changes in the DFG Fachsystematik every 4 years? The version of 2024 is available as a [PDF](https://www.dfg.de/resource/blob/331950/85717c3edb9ea8bd453d5110849865d3/fachsystematik-2024-2028-en-data.pdf) and we would like to use it to classify our datasets. I would like to have an ontology prefix that has the year/version as a part.

We are happy to contribute the newer version to the dfgfo, but would like to find a solution for the versioning first.

**Comment by doigl** [comment]
Great and sure, let's meet.


Am 15. Mai 2024 15:50:35 schrieb arndt ***@***.***>:

Hi @doigl<https://github.com/doigl> Good question! I'd love to work on that, too, and it's the time now, I guess. Shall we meet to discuss?

**Comment by andrecastro0o** [comment]
Good question @lsoehn
Why isn't it a skos:ConceptScheme?
I think at the time the reason to use sub-class instead of skos:broader and skos:narrower was due to fact that OLS didn't display skos relation and we wanted the DFG-Fachsystematik  terms to be displayed (as a tree) OLS.
But I am all for also having a skos version.
Any thoughts?

**Comment by SArndt-TIB** [comment]
> let me know if you need a hand with the process a
Will do, @andrecastro0o . 

@lsoehn A skos version would also be good. We could set this as a task here as well. I'd also love to set up working IDs for entities while we're at it.

I'll try to organise a meeting so that we could maybe all join, if you want and are available.

**Comment by andrecastro0o** [comment]
@SArndt-TIB @doigl  @lsoehn  do any of you wants to take this issue, or has a strategy for versioning?

I renamed the [releases](https://github.com/tibonto/DFG-Fachsystematik-Ontology/releases) of the 2020-2024 version 
`2020-2024 version (YYYY.MM.DD) `

I think when the 2024-2028 version is merged we can create a new release for it: `2024-2028 version (YYYY.MM.DD) `

Any thoughts?

**Comment by SArndt-TIB** [comment]
> @SArndt-TIB @doigl @lsoehn do any of you wants to take this issue, or has a strategy for versioning?
> 
> I renamed the [releases](https://github.com/tibonto/DFG-Fachsystematik-Ontology/releases) of the 2020-2024 version `2020-2024 version (YYYY.MM.DD) `
> 
> I think when the 2024-2028 version is merged we can create a new release for it: `2024-2028 version (YYYY.MM.DD) `
> 
> Any thoughts?

@andrecastro0o The renaming of the releases is very well, we should also do it like that for 2024-2028. When we start on #10 we should also think about versionIRIs. Could for example look like this www.purl.org/dfgfo/2024-2028/2024-07-02 or with w3id or whatever we will use.

**Comment by andrecastro0o** [comment]
@SArndt-TIB. thanks.
> @andrecastro0o The renaming of the releases is very well, we should also do it like that for 2024-2028. When we start on #10 we should also think about versionIRIs. Could for example look like this [www.purl.org/dfgfo/2024-2028/2024-07-02](http://www.purl.org/dfgfo/2024-2028/2024-07-02) or with w3id or whatever we will use.

I am happy with it, but I am not familiar with versionIRIs, and why they are necessary :stuck_out_tongue:  But I am happy if you lead that.

To sum up the versioning:
* Releases: `YYYY-YYYY version (YYYY.MM.DD) `
* IRIs: `http://www.purl.org/dfgfo/YYYY-YYYY/YYYY-MM-DD`

**Comment by doigl** [comment]
@SArndt-TIB : I would vote for just adding the year of introduction to whatever prefix, we agree on, so f.e. dfgfo2024: [http://www.purl.org/dfgfo/2024](http://www.purl.org/dfgfo/2024/) to keep the IRIs short.

what do you mean? And I am not sure, if we are still looking for a prefix or if we wanted to use the prefix from Jakob. I like the possibilities of w3id, but the question is, in what namespace of w3id we want to place the vocabulary/ontology.

**Comment by andrecastro0o** [comment]
@doigl  & @SArndt-TIB 
Actually, after doing a bit of reading and having come across recently the `ow:versionIRI` 

https://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI mentions that
>Each ontology MAY have an ontology IRI, which is used to identify an ontology. If an ontology has an ontology IRI, the ontology MAY additionally have a version IRI, which is used to identify the version of the ontology. The version IRI MAY be, but need not be, equal to the ontology IRI

Also `owl:versionInfo` could be useful to annotate this:
> The owl:versionInfo annotation property can be used to provide an IRI with a string that describes the IRI's version.   

Hence my preference is for the 2024 version to include the version in the versionIRI and versionInfo and remove the version from the title. If we agree to do so, the [metadata.ttl](metadata.ttl) would look like

``` ttl
<https://github.com/tibonto/dfgfo> rdf:type owl:Ontology ;
                                   dc:creator "Deutsche Forschungsgemeinschaft (DFG)",
                                              "André Castro",
                                              "Susanne Arndt";
                                   dc:description "DFG Fachsystematik Ontology / DFG Classification of Subject Areas Ontology (DFGFO) encodes the DFG Classification of Subject Areas into an ontology, where each subject number are is enconded into a Class with subclass statements following the DFG Classification of Subject Areas hierarchy. Labels are provide German and English.";
                                   dc:title "DFG Classification of Subject Areas Ontology "@en ;
                                   dc:title "DFG Fachsystematik - Ontologie "@de ;
                                   rdfs:comment "DFG Classification of Subject Areas Ontology is being created as part of the TIB Terminology Service"@de ;
                                   rdfs:comment "DFG Fachsystematik - Ontology wurde zur Integration in den TIB Terminology Service erstellt"@de ;
                                   terms:license <https://creativecommons.org/licenses/by/4.0/> . 
                                   owl:versionInfo "2024-2028" .
                                   owl:versionIRI  <https://github.com/tibonto/DFG-Fachsystematik-Ontology/releases/2023-01-17/dfgfo.ttl>
```


**I am more unsure about the future IRI**, I believe @SArndt-TIB  has a good idea about it, and is being handled in #10 


PS: I will try to move this discussion to a separate issue
