### ISSUE TITLE
Align with https://uri.gbv.de/terminology/dfg/

### ISSUE THREAD

**Issue by nichtich** [tibonto/DFG-Fachsystematik-Ontology#17]
The DFG Fachsystematik (BARTOC record and URI http://bartoc.org/en/node/520) has already been converted to RDF/SKOS at https://github.com/gbv/jskos-data/tree/master/dfg with URI and namespace http://uri.gbv.de/terminology/dfg/  (*the URIs are currently not resolveable because the web application at https://uri.gbv.de/terminology/ is being worked on*). Both versions should be aligned.

Apart from the URIs, the version <https://uri.gbv.de/terminology/dfg/> uses SKOS, so each class is a `skos:Concept` and hierarchy uses `skos:broader`/`skos:narrower`. Furthermore notations are included with `skos:notation`.

**Comment by andrecastro0o** [comment]
@nichtich @SArndt-TIB 
what is the plan here? That we include a SKOS version in this repo, or we keep them separate?

@nichtich  https://uri.gbv.de/terminology/dfg/  is not loading :/ just eternal spinning wheels show up :information_source:

**Comment by SArndt-TIB** [comment]
@andrecastro0o, @nichtich already provided an rdf+xml version of their SKOS version, but details will come later, see the mail from June 17th. You can already take a look: https://github.com/gbv/jskos-data/tree/dfg/dfg. We should discuss this in the next meeting.

**Comment by andrecastro0o** [comment]
align my including [owl:sameAs](https://www.w3.org/TR/owl-ref/#sameAs-def) statements in  DFO individual terms , pointing to http://uri.gbv.de/terminology/dfg/

```
dfgfo:116-03 a owl:Class ;
    rdfs:label "African, American and Oceania Studies"@en ;
    rdfs:subClassOf dfgfo:116 ;
    skos:altLabel "Afrika-, Amerika- und Ozeanienbezogene Wissenschaften"@de ;
    owl:sameAs <http://uri.gbv.de/terminology/dfg2024/116-03> .
```
(dots removed as #29 will be completed before this issue
