### ISSUE TITLE
use-cases of DFG-Fachsystematik-Ontology in README

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/DFG-Fachsystematik-Ontology#21]
I remember from our previous discussion, that DFG-Fachsystematik-Ontology is being used in a instance of the dataverse (@doigl I think you mentioned, right?)  and in TIB OLS (@SArndt-TIB is that the case?).

I suggest that we try to add a section with use-cases of DFG-Fachsystematik-Ontology in the README.

What do you think?

Can you help adding some examples? You can add to the issue, I can than put them in the README

cheers

**Comment by SArndt-TIB** [comment]
Hi @andrecastro0o, yeah, sounds great. In TIB TS we just index it, it is not used for metadata management of the indexed ontologies, though. Currently, there is the 2020 version: https://terminology.tib.eu/ts/ontologies/dfgfo. We could mention that. 

In the Dataverse instance DaRUS it is used to tag datasets. Here is an example: https://darus.uni-stuttgart.de/dataset.xhtml?persistentId=doi:10.18419/darus-3988 where you find the reference to here in the field "topic classification". It's also used in the facets of the instance, e.g. you can filter for dfgfo-topics, e.g. https://darus.uni-stuttgart.de/dataverse/darus?q=*&fq1=topicClassValue_ss%3A%22Computer+Science+%28%28DFGFO%29%29%22&fq0=dvObjectType%3A%28dataverses+OR+datasets+OR+files%29&types=dataverses%3Adatasets%3Afiles&sort=score&order=

Maybe the others can add more.

**Comment by andrecastro0o** [comment]
Thanks for the input @SArndt-TIB 
Before our next meeting I plan to add to the README the section Use-cases of DFG-Fachsystematik-Ontology,
mentioning the Dataverse instance DaRUS. And a "Using the DFG-Fachsystematik-Ontology? We would like to hear from you (via an issue), and include your use-case in this section"

**Comment by SArndt-TIB** [comment]
Thanks, @andrecastro0o That's a great idea!
