### ISSUE TITLE
dfgfo.ttl contains invalid line breaks

### ISSUE THREAD

**Issue by milkbread** [tibonto/DFG-Fachsystematik-Ontology#8]
The current versions seems to be no valid ttl, as there are a lot of line breaks. 
For example:

`<https://github.com/tibonto/dfgfo/101
>`

On the other side...why isn't it referenced via prefix?

**Comment by SArndt-TIB** [comment]
Dear @milkbread, 

thanks for reporting the issue. The file has been created from the csv file and the serialization is done by rdflib. I am not quite sure yet why the line breaks are inserted or the items are not prefixed. I'll have to look into the details.

As far as I can see, Protege has no problem processing it. We are also indexing it in an instance of the Ontology Lookup Service (OLS) where the line breaks did not cause any problems, either. On each commit, the file is processed by robot to generate a report on several aspects. This was also able to use the file despite line breaks. I was wondering in which environment you'd like to use the ontology? Maybe you could provide more information about which problems you encountendered.

Thank you and best regards

Susanne

**Comment by milkbread** [comment]
Dear Susanne,

thanks for your reply!

I was not able to push the *.ttl to an instance of Jena Fuseki, ending up in a 400. 
Therefore I analysed the file with a validator which returned this problem. 

`Unexpected "<https://github.com/tibonto/dfgfo/101" on line 29.`

But I could also have seen it in the logs of Fuseki:

`
[2022-12-15 12:54:08] Fuseki     ERROR [line: 30, col: 1 ] Broken IRI (newline): https://github.com/tibonto/dfgfo/101
[2022-12-15 12:54:08] Fuseki     INFO  [1619] 400 Parse error: [line: 30, col: 1 ] Broken IRI (newline): https://github.com/tibonto/dfgfo/101 (26 ms)
`
Cheers Ralf

**Comment by SArndt-TIB** [comment]
Hi @milkbread, 
both issues should be fixed in branch https://github.com/tibonto/DFG-Fachsystematik-Ontology/tree/8-dfgfottl-contains-invalid-line-breaks. Give me a short heads up and I'll merge.

Thanks, 
Susanne

**Comment by milkbread** [comment]
Hi Susanne,

unfortunately no.
'dfgfo.ttl' has now an encoding-issue and fuseki is complaining about: 

'400 Character Coding Error: java.nio.charset.MalformedInputException: Input length = 1 (70 ms)'

I can see it in my IDE: 

![image](https://user-images.githubusercontent.com/1375004/211562156-12e8e83e-2706-4297-a7ba-b6af1992c828.png)

Fuseki excepts it as soon as I change it to 'utf-8'!

So I was wondering where this wrong encoding comes from, ran the code and found out that:

1. the fix breakes the code as splitting ('\r\n') doesn't work
2. a perfect 'dfgfo.ttl' gets created on the main branch

Sorry, I should have tried that before ;)

So it looks like, as if the failures resulted from manual editing. Is that possible?

Cheers,
Ralf

**Comment by SArndt-TIB** [comment]
Ah, damn, yeah it works on my system. I reverted the change in the script, but then I create a file with invalid line breakes again. Could you do me a favor and a) check the encoding of the updated dfgfo.ttl now and b) run the script and upload your dfgfo.ttl?

**Comment by milkbread** [comment]
Yes...it works like a charm and produces a perfect *.ttl, which I can upload to Fuseki without any problem!

Could it mean, that your *.csv contains '\r'-characters, which are not in my cloned version?

**Comment by SArndt-TIB** [comment]
Yep, I have CLRF while you apparently have LF, so the problem was introduced on my system. I have to adjust for this before running the script and uploading the dfgfo.ttl. I am not sure whether it worked. Could you try out this file for a last test? Thanks a lot!

https://raw.githubusercontent.com/tibonto/DFG-Fachsystematik-Ontology/8-dfgfottl-contains-invalid-line-breaks/dfgfo.ttl

**Comment by milkbread** [comment]
Good morning,

basically it works! But there is a new encoding issue as den special character of Andr**é** is broken:

![image](https://user-images.githubusercontent.com/1375004/211742495-a75fd883-63da-4015-b077-4c928f1b3539.png)

And it is not a problem in visualisation, it persists until the final import:

![image](https://user-images.githubusercontent.com/1375004/211743327-f61d5486-f6b4-4c86-9458-23faca6ae86b.png)

Maybe we could handle the CLRF vs LF problem by replacing both of them!?

`id, label = id_n_label.replace('\r', '|').replace('\n', '|').split('|')`

**Comment by SArndt-TIB** [comment]
Hi @milkbread, the encoding should be properly done for all Literals now. I also added some instructions to use end of line sequence LF when applying the script to create the ontology. Your suggested replacements did not work out depending on whether I use CLRF or LF for the csv.

So, how does it go?
https://raw.githubusercontent.com/tibonto/DFG-Fachsystematik-Ontology/8-dfgfottl-contains-invalid-line-breaks/dfgfo.ttl

**Comment by milkbread** [comment]
Perfect :)

**Comment by SArndt-TIB** [comment]
Okay, nice. Thanks for your support!
