### ISSUE TITLE
103+ subjects have '102 History' assigned as Review Board

### ISSUE THREAD

**Issue by milkbread** [tibonto/DFG-Fachsystematik-Ontology#9]
I am facing the problem that there is no '103	Art History, Music, Theatre and Media Studies' in the ontology.
I found out, that this comes from the XLSX ([Fachsystematik_2020-2024_EN_20210621.xlsx](https://github.com/tibonto/DFG-Fachsystematik-Ontology/blob/main/csv/Fachsystematik_2020-2024_EN_20210621.xlsx)) as well as the CSV ([Fachsystematik_2020-2024.csv](https://github.com/tibonto/DFG-Fachsystematik-Ontology/blob/main/csv/Fachsystematik_2020-2024.csv)) as all 103-* items have assigned '102 History' as Review Board.

Now the big question...is it a bug or a feature? ;)

Cheers Ralf

**Comment by SArndt-TIB** [comment]
It is what it is ;-) That's how we got it, if I see correctly. The PDFs seems to be the correct source for this category. I will correct the csv as soon as I get your feedback on #8 . Thanks again :-)

All the best to you, Susanne

**Comment by SArndt-TIB** [comment]
@milkbread Here is another update, adding 103 as a concept and assigning 103-xx correctly. I updated this in the csv, based on the Excel file [Fachsystematik_2020-2024_2020629.xlsx](https://github.com/tibonto/DFG-Fachsystematik-Ontology/blob/main/csv/Fachsystematik_2020-2024_2020629.xlsx). Is that okay?

**Comment by milkbread** [comment]
Hi Susanne,

yes, perfect! That fixes it as intended!

So we simply leave the XLSX with english labels ([Fachsystematik_2020-2024_EN_20210621.xlsx](https://github.com/tibonto/DFG-Fachsystematik-Ontology/blob/main/csv/Fachsystematik_2020-2024_EN_20210621.xlsx)) as it is?

Thank you very much!

**Comment by SArndt-TIB** [comment]
I would suggest to leave them like they are, since these are our original sources, while the csv is a resource which was created from it. Thanks for your feedback!
